#avant(fichier original)
#scara_cpe_controller:
    #controller:
        #package: dynamixel_controllers
        #module: joint_trajectory_action_controller
        #type: JointTrajectoryActionController
    #joint_trajectory_action_node:
        #min_velocity: 0.1
        #constraints:
            #goal_time: 0.5
#apres avec le robot reel
scara_cpe:
  scara_cpe_controller:
      controller:
          package: dynamixel_controllers
          module: joint_trajectory_action_controller
          type: JointTrajectoryActionController
      joint_trajectory_action_node:
          min_velocity: 0.1
          constraints:
              goal_time: 0.5
